name: Trunk Analytics Uploader
author: trunk.io
description: Uploads test results to trunk.io

inputs:
  junit-paths:
    description: Comma-separated list of glob paths to junit files.
    required: false
  org-slug:
    description: Organization slug.
    required: true
  token:
    description: Organization token. Defaults to TRUNK_API_TOKEN env var.
    required: false
  repo-head-branch:
    description: Value to override branch of repository head.
    required: false
  run:
    description: The command to run before uploading test results.
    required: false
  tags:
    description: Comma separated list of custom tag=value pairs.
    required: false
  repo-root:
    description: The root directory of the repository.
    required: false
  cli-version:
    description: The version of the uploader to use.
    required: false
    default: 0.6.19
  team:
    description: Value to tag team owner of upload.
    required: false
  xcresult-path:
    description: Path to the xcresult directory.
    required: false
  bazel-bep-path:
    description: Path to the bazel BEP file to parse in place of junits.
    required: false
  quarantine:
    description: Whether or not to allow quarantining of failing tests.
    required: false
  allow-missing-junit-files:
    description: Whether or not to allow missing junit files in the upload invocation.
    required: false
    default: true

runs:
  using: composite
  steps:
    - name: Upload test results
      run: ${GITHUB_ACTION_PATH}/script.sh ${{ inputs.run }}
      shell: bash
      continue-on-error: ${{ inputs.run == '' && (inputs.quarantine == '' || inputs.quarantine == 'false') }}
      env:
        JUNIT_PATHS: ${{ inputs.junit-paths }}
        ORG_URL_SLUG: ${{ inputs.org-slug }}
        INPUT_TOKEN: ${{ inputs.token }}
        REPO_HEAD_BRANCH: ${{ inputs.repo-head-branch }}
        REPO_ROOT: ${{ inputs.repo-root }}
        TAGS: ${{ inputs.tags }}
        CLI_VERSION: ${{ inputs.cli-version }}
        TEAM: ${{ inputs.team }}
        QUARANTINE: ${{ inputs.quarantine }}
        XCRESULT_PATH: ${{ inputs.xcresult-path }}
        ALLOW_MISSING_JUNIT_FILES: ${{ inputs.allow-missing-junit-files }}
        BAZEL_BEP_PATH: ${{ inputs.bazel-bep-path }}
