name: Trunk Analytics Uploader
author: trunk.io
description: Uploads test results to trunk.io

inputs:
  junit-paths:
    description: Comma-separated list of glob paths to junit files.
    required: false
  org-slug:
    description: Organization slug.
    required: true
  token:
    description: Organization token. Defaults to TRUNK_API_TOKEN env var.
    required: false
  repo-head-branch:
    description: Value to override branch of repository head.
    required: false
  run:
    description: The command to run before uploading test results.
    required: false
  tags:
    description: Comma separated list of custom tag=value pairs. This is deprecated and will be removed in a future release.
    required: false
  repo-root:
    description: The root directory of the repository.
    required: false
  cli-version:
    description: The version of the uploader to use.
    required: false
    default: latest
  team:
    description: Value to tag team owner of upload.
    required: false
  xcresult-path:
    description: Path to the xcresult directory.
    required: false
  bazel-bep-path:
    description: Path to the bazel BEP file to parse in place of junits.
    required: false
  quarantine:
    description: Whether or not to allow quarantining of failing tests.
    required: false
  allow-missing-junit-files:
    description: Whether or not to allow missing junit files in the upload invocation.
    required: false
    default: true
  hide-banner:
    description: Whether to hide the top level flaky tests banner
    required: false
  variant:
    description: User specified variant of a set of tests being uploaded.
    required: false
  use-uncloned-repo:
    description: Set to 'true' if your tests do not require cloning the repository under test,
    required: false
    default: false

runs:
  using: composite
  steps:
    - name: Upload test results
      run: ${GITHUB_ACTION_PATH}/script.sh ${{ inputs.run }}
      shell: bash
      env:
        JUNIT_PATHS: ${{ inputs.junit-paths }}
        ORG_URL_SLUG: ${{ inputs.org-slug }}
        INPUT_TOKEN: ${{ inputs.token }}
        REPO_HEAD_BRANCH: ${{ inputs.repo-head-branch }}
        REPO_ROOT: ${{ inputs.repo-root }}
        TAGS: ${{ inputs.tags }}
        CLI_VERSION: ${{ inputs.cli-version }}
        TEAM: ${{ inputs.team }}
        QUARANTINE: ${{ inputs.quarantine }}
        XCRESULT_PATH: ${{ inputs.xcresult-path }}
        ALLOW_MISSING_JUNIT_FILES: ${{ inputs.allow-missing-junit-files }}
        BAZEL_BEP_PATH: ${{ inputs.bazel-bep-path }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        HIDE_BANNER: ${{ inputs.hide-banner }}
        VARIANT: ${{ inputs.variant }}
        USE_UNCLONED_REPO: ${{ inputs.use-uncloned-repo }}
        GH_REPO_URL: ${{ github.event.pull_request.head.repo.html_url }}
        GH_REPO_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        GH_REPO_HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}
        GH_REPO_HEAD_COMMIT_EPOCH: ${{ github.event.pull_request.updated_at }}
        GH_REPO_HEAD_AUTHOR_NAME: ${{ github.event.pull_request.head.user.name }}
        GH_REPO_HEAD_AUTHOR_EMAIL: ${{ github.event.pull_request.head.user.email }}
