name: Trunk Analytics Uploader
author: trunk.io
description: Uploads test results to trunk.io

inputs:
  junit-paths:
    description: Comma-separated list of glob paths to junit files.
    required: false
  org-slug:
    description: Organization slug.
    required: true
  token:
    description: Organization token. Defaults to TRUNK_API_TOKEN env var.
    required: false
  repo-head-branch:
    description: Value to override branch of repository head.
    required: false
  run:
    description: The command to run before uploading test results.
    required: false
  repo-root:
    description: The root directory of the repository.
    required: false
  cli-version:
    description: The version of the uploader to use.
    required: false
    default: latest
  xcresult-path:
    description: Path to the xcresult directory.
    required: false
  bazel-bep-path:
    description: Path to the bazel BEP file to parse in place of junits.
    required: false
  quarantine:
    description: Whether or not to allow quarantining of failing tests.
    required: false
  allow-missing-junit-files:
    description: Whether or not to allow missing junit files in the upload invocation.
    required: false
    default: true
  hide-banner:
    description: Whether to hide the top level flaky tests banner
    required: false
  variant:
    description: User specified variant of a set of tests being uploaded.
    required: false
  verbose:
    description: Enable verbose logging
    default: false
    required: false
    type: boolean
  use-uncloned-repo:
    description: Set to 'true' if your tests do not require cloning the repository under test,
    required: false
    default: false
    type: boolean
  previous-step-outcome:
    description: The outcome of the previous step in the workflow. Set this equal to steps.[id].outcome where `[id]` is the id of the corresponding test run.
    required: false
  # these are automatically grabbed inputs
  # it is recommended to leave these as is and not specify them when running this action
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
  pr-title:
    description: The Title of the Pull Request (if being run inside one)
    default: ${{ github.event.pull_request.title }}
  gh-repo-url:
    description: The URL of the GitHub repo
    default: ${{ github.event.pull_request.head.repo.html_url }}
  gh-repo-head-sha:
    description: The head commit of the pull request
    default: ${{ github.event.pull_request.head.sha }}
  gh-repo-head-branch:
    description: The head branch of the pull request
    default: ${{ github.event.pull_request.head.ref }}
  gh-repo-head-commit-epoch:
    description: The commit timestamp
    default: ${{ github.event.pull_request.updated_at }}
  gh-repo-head-author-name:
    description: The actor triggering the action
    default: ${{ github.actor }}
  gh-action-ref:
    description: The ref of the action being used
    default: ${{ github.action_ref }}
  show-failure-messages:
    description: Show failure outputs in upload. This is experimental, do not rely on this.
    type: boolean
    default: false
  dry-run:
    description: Run without uploading the results to the server. They will instead be dumped to the directory that the action is run in.
    type: boolean
    default: false
    required: false
  use-cache:
    description: Enable caching of the trunk-analytics-cli binary to reduce subsequent downloads
    type: boolean
    default: false
    required: false

runs:
  using: node20
  main: dist/index.js
