name: Trunk Analytics Uploader
author: trunk.io
description: Uploads test results to trunk.io

inputs:
  junit-paths:
    description: Comma-separated list of glob paths to junit files.
    required: true
  org-slug:
    description: Organization slug.
    required: true
  token:
    description: Organization token. Defaults to TRUNK_API_TOKEN env var.
    required: false
  repo-head-branch:
    description: Value to override branch of repository head.
    required: false
  run:
    description: The command to run before uploading test results.
    required: false
  tags:
    description: Comma separated list of custom tag=value pairs.
    required: false
  repo-root:
    description: The root directory of the repository.
    required: false
  cli-version:
    description: The version of the uploader to use.
    required: false
    default: 0.5.19
  team:
    description: Value to tag team owner of upload.
    required: false

runs:
  using: composite
  steps:
    - name: Upload test results
      run: ${GITHUB_ACTION_PATH}/script.sh ${{ inputs.run }}
      shell: bash
      continue-on-error: ${{ inputs.run == '' }}
      env:
        JUNIT_PATHS: ${{ inputs.junit-paths }}
        ORG_URL_SLUG: ${{ inputs.org-slug }}
        INPUT_TOKEN: ${{ inputs.token }}
        REPO_HEAD_BRANCH: ${{ inputs.repo-head-branch }}
        REPO_ROOT: ${{ inputs.repo-root }}
        TAGS: ${{ inputs.tags }}
        CLI_VERSION: ${{ inputs.cli-version }}
        TEAM: ${{ inputs.team }}
