name: Trunk Analytics Uploader
author: trunk.io
description: Uploads test results to trunk.io

inputs:
  junit-paths:
    description: Comma-separated list of glob paths to junit files.
    required: false
  org-slug:
    description: Organization slug.
    required: true
  token:
    description: Organization token. Defaults to TRUNK_API_TOKEN env var.
    required: false
  repo-head-branch:
    description: Value to override branch of repository head.
    required: false
  run:
    description: The command to run before uploading test results.
    required: false
  tags:
    description: Comma separated list of custom tag=value pairs. This is deprecated and will be removed in a future release.
    required: false
  repo-root:
    description: The root directory of the repository.
    required: false
  cli-version:
    description: The version of the uploader to use.
    required: false
    default: latest
  team:
    description: Value to tag team owner of upload.
    required: false
  xcresult-path:
    description: Path to the xcresult directory.
    required: false
  bazel-bep-path:
    description: Path to the bazel BEP file to parse in place of junits.
    required: false
  quarantine:
    description: Whether or not to allow quarantining of failing tests.
    required: false
  allow-missing-junit-files:
    description: Whether or not to allow missing junit files in the upload invocation.
    required: false
    default: true
  hide-banner:
    description: Whether to hide the top level flaky tests banner
    required: false
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
  variant:
    description: User specified variant of a set of tests being uploaded.
    required: false

runs:
  using: node20
  main: dist/index.js
